# Generated by Django 4.2.7 on 2023-11-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('plate_num', models.CharField(max_length=12)),
                ('price_day', models.DecimalField(decimal_places=3, max_digits=10)),
                ('codition', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
    ]
