# Generated by Django 4.2.7 on 2023-11-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_plate_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='codition',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
