# Generated by Django 4.2.7 on 2023-11-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_codition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='codition',
            field=models.CharField(default='free', max_length=8, null=True),
        ),
    ]
