# Generated by Django 4.2.7 on 2023-11-22 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_vehicle_codition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='codition',
            new_name='condition',
        ),
    ]
