# Generated by Django 4.2.7 on 2023-11-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_rename_codition_vehicle_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='condition',
            field=models.CharField(blank=True, default='free', max_length=8),
        ),
    ]
